site_name: Тестологий # Тестологенты иметрий
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.annotate
plugins:
  - search
language: ru
extra:\n  annotation: true
  social:
    - icon: material/web\n      link: 'https://starline.ru'
      name: Скидко твери